geometry:
  win_size: [ 720, 480 ]
lines:
  score:
    start_pos: [ 480, 0 ]
    end_pos: [480, 480]
colors:
  bg: [ 0, 0, 0 ]
  border: [ 255, 255, 0 ]
  font: [ 0, 255, 0 ]
  info: [ 130, 250, 120 ]
  warning: [ 255, 0, 255 ]
caption: 'Snake Game v1.0'
font:
  name: 'assets/fonts/RobotWorldItalic.ttf'
  size: 25
fps: 60
snake_init:
  pos: [ 15, 5 ]
  length: 5
  speed: 5
  direction: 'right'